### ISSUE TITLE
Install from pip fails

### ISSUE THREAD

**Issue by patrick-brian-mooney** [hotzenklotz/pybeerxml#2]
I've tried installing with `pip install pybeerxml`, `pip install -U pybeerxml`, and `sudo pip install pybeerxml`, plus tried replacing `pip` with `pip3` in all of those; I've also tried purging the pip cache between each attempt. All of these attempts give me some close variation on:

    sudo pip install pybeerxml
    Collecting pybeerxml
      Using cached pybeerxml-1.0.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-gknj4krg/pybeerxml/setup.py", line 5, in <module>
            import pybeerxml
          File "/tmp/pip-build-gknj4krg/pybeerxml/pybeerxml/__init__.py", line 1, in <module>
            from recipe import Recipe
        ImportError: No module named 'recipe'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gknj4krg/pybeerxml/
    00:39:21 patrick@linawesome _posts$ sudo pip install pybeerxml
    Collecting pybeerxml
      Downloading pybeerxml-1.0.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-onobhrs7/pybeerxml/setup.py", line 5, in <module>
            import pybeerxml
          File "/tmp/pip-build-onobhrs7/pybeerxml/pybeerxml/__init__.py", line 1, in <module>
            from recipe import Recipe
        ImportError: No module named 'recipe'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-onobhrs7/pybeerxml/

It looks to me like the code is trying to run itself during the install (`from recipe import Recipe`) but before it's fully installed, preventing the installation from completing. No?

I'm running 64-bit Python 2.7.9 and Python 3.4.2 under Crunchbang++ Linux, a Debian derivative.

**Comment by hotzenklotz** [comment]
@patrick-brian-mooney Thanks for letting me know. I just released a new version of PyBeerXML. I believe that should fix these issues. Do you mind testing again?

**Comment by patrick-brian-mooney** [comment]
Works for me now, @hotzenklotz ! Thanks!

Excited to have Python3 compatibility, too. :)

**Comment by hotzenklotz** [comment]
@patrick-brian-mooney That's good to know :-) Have you tried both Python 2 & 3?

**Comment by patrick-brian-mooney** [comment]
I have! Sorry, I could have been more specific originally. Both installed and a cursory test shows I can import and examine them from an interactive shell.

Dunno if you have any interest in tracking what people do with your code, but I use pybeerxml in a script that automates some of the dull work involved in maintaining my brewing log: https://github.com/patrick-brian-mooney/beerxml-to-hrecipe

Thanks for a great bit of code! I appreciate it.
